### ISSUE TITLE
Incompatible with CC 1.4.0

### ISSUE THREAD

**Issue by Demariosphere** [ZeikJT/CrossCodeCheats#2]
It's written that this mod is compatible with version >1.2 and <1.4 when I starting the game.

**Comment by ZeikJT** [comment]
Ah, didn't realize there was a new version out! (or the DLC)
Will check that things still work and then bump the version or you can test it for yourself and let me know!
Just need to change the version for crosscode in package.json.

**Comment by Demariosphere** [comment]
You should play the new version, worth the price.
So I just change the version in the package.json and all works?
I'll gladly try it right now, but it's my working time. I'll try this evening.

**Comment by ZeikJT** [comment]
I have changed the version restriction to be more lenient and just allow all future versions of the game. I also sent out a pull request to the CCLoader ModDB to update the version they have available, once that's merged I'll consider this issue closed:
https://github.com/CCDirectLink/CCModDB/pull/133

**Comment by ZeikJT** [comment]
Looks like it has been merged so this shouldn't be an issue anymore, thanks for the report!
