### ISSUE TITLE
100% resist is always on

### ISSUE THREAD

**Issue by kygil85** [ZeikJT/CrossCodeCheats#5]
I have the cheat 100% all resistances off, but my character still has 100% resist when checking their status.

**Comment by remghoost** [comment]
I had this issue as well. It persisted past restarts of the game too.

I seemed to have fixed it in a stupid roundabout way though.
Change the true to a false on this line.

https://github.com/ZeikJT/CrossCodeCheats/blob/1cea15af4606714ff90ddc525d8480018040198a/cheats.js#L34

It'll be in `assets\mods\CrossCodeCheats-1.4.0`

Not sure why changing the default fixes the issue, but it does.
I'd say that all of these should be set to `false` by default, but eh.
It's an old project for an old game. It works fine enough.

**Comment by kygil85** [comment]
Thanks for the quick fix remghoost

**Comment by ZeikJT** [comment]
Haven't been on here in a while and didn't see this until now, sorry about that! Thanks @remghoost for the fix and suggestion to change the defaults. Done in #6 now.
